### ISSUE TITLE
The @default(now()) doesn't work with SQLite

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/photonjs#103]
The following definition of a model field:
`startMoment DateTime @default(now())`
doesn't enforce 'startMoment' to have a default value in SQLite. 

In db browser, schema of the field looks like this: 
`"startMoment" DATE NOT NULL`
that is, there is nothing about a default value. 

Consequently, startMoment is still required at creation of containing node, like:
`photon.nodes.create({data})`
here, if data contains no 'startMoment' property, an error will be thrown.

PS: The https://github.com/prisma/photonjs/issues/29 issue seems to be similar and it's closed, but the issue does still present.

**Comment by Errorname** [comment]
`@default(now())` works for me in SQLite, but only for `createdAt`. And even then, I must have at least one attribute in data during creation (doing `photon.thing.create({data:{}})` will throw)

**Comment by mavilein** [comment]
This is fixed with: https://github.com/prisma/prisma/pull/4774
This will ship with `preview4`.
