### ISSUE TITLE
Dynamic dependency encoding

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#115]
Generated photon has a dynamic unresolved dependency `require('encoding')`, that looks like a peer dep for a photon dependency bundled by `ncc`. 

Bundlers bundling `Photon` code do not like this. 

To reproduce, try to run `Photon` generated code through a bundler (like `now dev` => `ncc`) for example. 

The following error/warning (depending on the bundler) can be observed
<img width="763" alt="CleanShot 2019-07-05 at 14 34 49@2x" src="https://user-images.githubusercontent.com/746482/60825651-7754be00-a1ac-11e9-9a91-70047539a1ae.png">

**Comment by timsuchanek** [comment]
Dependency to `encoding` removed in latest version

**Comment by auderer** [comment]
Still having this issue with `prisma2@2.0.0-preview-1`

**Comment by divyenduz** [comment]
@auderer : Thanks for reporting this, did you regenerate Photon using `prisma2 generate` after upgrading to `prisma2@2.0.0-preview-1`?
