### ISSUE TITLE
Generate relative to Prisma schema file

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#125]
For a project structure like this 

```
.
- prisma/schema.prisma
- functions/
```

To generate Photon into the `functions` folder, we need a generator config like this: 

```
generator photon {
    provider = "photonjs"
    output   = "./functions/generated/photon"
}
```

It should be like this (i.e. relative to the schema.prisma file path): 

```
generator photon {
    provider = "photonjs"
    output   = "../functions/generated/photon"
}
```

**Comment by timsuchanek** [comment]
Fixed in latest version.
