### ISSUE TITLE
GraphQL example is shipping unused code

### ISSUE THREAD

**Issue by pantharshit00** [prisma/photonjs#133]
Version: prisma2@2.0.0-alpha.5, binary version: 30a33bde5b1d9f79e0a48491749528da76002e24

Currently, Prisma2 is shipping with unused SDL first code which is not being used. Only `index.js` file is needed which is using GraphQL Nexus.

![image](https://user-images.githubusercontent.com/22195362/61212007-a1632e80-a71e-11e9-8015-854fbffb89f8.png)

Reproduction:
1. Run `prisma init`
2. SQLite > JS > Select both photon and lift > GraphQL Server

**Comment by janpio** [comment]
Can you please retest this with the new `init` flow @pantharshit00 and apply the `candidate` label if it is still the case? Thanks.

**Comment by pantharshit00** [comment]
I am no longer able to reproduce this.
