### ISSUE TITLE
Cannot update with null or undefined

### ISSUE THREAD

**Issue by Errorname** [prisma/photonjs#148]
I am trying to remove a value from an optional property, but I cannot find how to do it.

**schema.prisma**
```
datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

generator photon {
  provider = "photonjs"
}

model User {
  id   String  @default(cuid()) @id @unique
  name String?
}
```

**index.js**
```js
const user = await photon.users.create({
    data: {
      name: 'The User'
    }
  })
  const updatedUser = await photon.users.update({
    where: {
      id: user.id
    },
    data: {
      name: null
    }
  })
  console.log({ user, updatedUser })
```

**Console**
```
Argument name: Got invalid value null on photon.updateOneUser. Provided null, expected String.
```

**Note:** If I use `undefined` instead of `null`, I won't have an error, but the user and updatedUser will have the same values so it doesn't work either

**Comment by gihrig** [comment]
@Errorname because, as the error says `expected String`, what happens if you set the value to an empty string `''` ?

I understand the practice of using null to designate fields that have no value assigned, but in the pattern of type safety, `name` being of type string, it seems that `null` (type object) and `undefined` (type undefined) would be invalid. Whereas `''` (type string) should be allowed.

Thoughts?

**Comment by Errorname** [comment]
When setting `''`, I have an empty string on the field, but that is not what I want.

In my opinion, an empty string and `null` are different in essence. It is the same as the difference between `0` for an Int and `null`. On one hand, you have a value (whatever it is and how it is interpreted as) and on the other hand, you don't have a value. An empty string isn't always interpreted as "not a value".

Moreover, I find it strange that when you create with an optional field you would have `null` on the field, but when you want to remove it, you then have `''`. That's not consistent

**Comment by sk8Guerra** [comment]
I also want to insert null to field in Postgres... have you achieved it in any way?
