### ISSUE TITLE
NullValueConstraint error when creating a record with all default fields and connecting to another record

### ISSUE THREAD

**Issue by tylerjbainbridge** [prisma/photonjs#150]
jwts is a table with only an id, createdAt,  updatedAt, and a user relation.

```js
const jwt = await photon.jwts.create({
	data: {
		connect: {
			user: { id },
		},
	},
});
```

**Comment by timsuchanek** [comment]
@tylerjbainbridge can you share your `jwts` and `user` model and the full error you get?

**Comment by janpio** [comment]
Remind @tylerjbainbridge 🐤

**Comment by tylerjbainbridge** [comment]
Sorry- didn't see the first message. 

I haven't run into this problem since and I've since abandoned this pet project, I'd say it's been fixed as a side effect of some of the improvements made over the last month or so 👍 

I'll let you know if I run into this again.
