### ISSUE TITLE
Allow empty "where" filters

### ISSUE THREAD

**Issue by auderer** [prisma/photonjs#152]
It would be great to allow the `where` parameter to be empty and contain undefined fields.

```js
photon.users.findMany({
  where: {
    // any undefined values will be ignored in filtering
    country,
    gender,
    company,
    membership
  }
})
```

Any `undefined` field in the `filter` object would be ignored.
So, `.find({ filter: { country: undefined } })` would just return all objects.

Current usage: (in this example, my resolver's fields are all optional)

```js
({ country, gender, company, membership }) => {
  const where = {}
  if (country) where.country = country
  if (gender) where.gender = gender
  if (company) where.company = company
  if (membership) where.membership = membership

  if (Object.keys(where).length > 0) {
    return photon.users.findMany({ where })
  } else {
    return photon.users.findMany()
  }
}
```

As you can see, I have to manually build a `where` object by checking every value I want to filter. Then I have to make sure the where object isn't empty before passing it in.

With my proposal, this becomes extremely simple:
```js
({ country, gender, company, membership }) => {
  return photon.users.findMany({
    where: {
      country,
      gender,
      company,
      membership
    }
  })
}
```

Or, I could even do this, if all my args are used for filtering:
```js
(args) => photon.users.findMany({ where: args })
```

**Comment by timsuchanek** [comment]
Note, while this is fixed from the TypeScript side, we still need to wait for #136 to allow empty `where: {}` from the Rust side.
