### ISSUE TITLE
Results in docs are incorrect in Photon website

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/photonjs#161]
I was checking https://photonjs.prisma.io/ & found some errors in results.

In `Field Selection`, I found `Select Exclusively` & `Include Additionally` have incorrect results. Idk about others but they might have incorrect results too.

**Comment by pantharshit00** [comment]
Yes, you are correct. We will fix that. 

Thanks for the heads up!

**Comment by pantharshit00** [comment]
Fixed!
