### ISSUE TITLE
Best practices for the managing the Photon object(s)?

### ISSUE THREAD

**Issue by artemzakharov** [prisma/photonjs#169]
I'm currently building an Express-based back end that leverages Photon to access the database, and while just about everything is going great, I'm somewhat unsure how I should manage the Photon "object". My architecture is based on routes and sub-routes, and looks like this:

**/api/index.ts**:
```
import { Router } from 'express';

const router = Router();

router.use('/get-foos', require('./get-foos'));

module.exports = router;
```
**/api/get-foos.ts**
```
import { Router } from 'express';
import Photon from '@generated/photon';

const router = Router();
const photon = new Photon();

router.get('/', async (req, res) => {
  const result = await photon.foos.findMany({...})
  res.send(result);
});

module.exports = router;
```
This works exactly as expected, but the part that I'm unsure about is whether I'm doing something wrong by essentially creating a new Photon object in each and every file that accesses the database; for comparison, in the original Prisma, I'd only ever initialize a single Prisma object (during server startup), and then pass that around with the "Context" pattern instead, effectively re-using the same single object in each instance.

Should I find some way to implement a similar Context pattern with Photon? Or is the way I'm doing it now (`const photon = new Photon();` in every individual file that needs DB access) perfectly fine?

**Comment by pantharshit00** [comment]
I will not suggest instantiating photon each time as it is not a singleton unlike mongoose and it will spawn a new instance of the prisma query engine.

What you can do is to create a db file which will instanstiate and export photon object:

```js
// utils/db.js
import Photon from '@generated/photon';

const photon = new Photon(); // provide options

export default photon
```

Now you can use this object everywhere.

**Comment by artemzakharov** [comment]
Great, thanks for clearing that up for me.
