### ISSUE TITLE
Crash when running with docker (node:alpine image)

### ISSUE THREAD

**Issue by 592da** [prisma/photonjs#173]
Hello 👋 

First of all, have to save that the idea of prisma2 is brilliant, thanks for the team that working for this amazing project.

The issue:

Tried to run photon with Docker,  (base image node:alpine)
Globally installed with ```npm install prisma2 -g --unsafe-perm```,

```
core_1   | Error: spawn /server/node_modules/@generated/photon/runtime/query-engine-linux-glibc-libssl1.1.0 ENOENT
core_1   |     at Process.onexit (internal/child_process.js:264:19)
core_1   |     at onErrorNT (internal/child_process.js:456:16)
core_1   |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
core_1   |   errno: 'ENOENT',
core_1   |   code: 'ENOENT',
core_1   |   syscall: 'spawn /server/node_modules/@generated/photon/runtime/query-engine-linux-glibc-libssl1.1.0',
core_1   |   path: '/server/node_modules/@generated/photon/runtime/query-engine-linux-glibc-libssl1.1.0',
core_1   |   spawnargs: []
core_1   | }
```

when trying to run ```prisma2 generate``` inside the container:
```
[migration-engine] error: Error: spawn /usr/local/lib/node_modules/prisma2/migration-engine ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /usr/local/lib/node_modules/prisma2/migration-engine',
  path: '/usr/local/lib/node_modules/prisma2/migration-engine',
  spawnargs: []
}
```

any thoughts ?

**Comment by olup** [comment]
Amazing, I am having the same problem, only forty minutes after you. Same situation, docker from alpine with node and npm installed, prisma2 installed globally, cannot genearte, got this half of a message : 
```
[migration-engine] error: Error: spawn /usr/lib/node_modules/prisma2/migration-engine ENOENT
Error: Error in lift engine: 
The command '/bin/sh -c prisma2 generate' returned a non-zero code: 1
```

**Comment by olup** [comment]
It's running when using node:latest as an image. Maybe it's the alpine images ?

**Comment by 592da** [comment]
> It's running when using node:latest as an image. Maybe it's the alpine images ?

@olup `latest` and `alpine` are different images, they both based on latest nodejs, but `alpine` runs on lighter environment (os), as far as I know, hope I am not causing confusion.

in any case it confirms that is an issue that not related only to `node:alpine` image...

**Comment by olup** [comment]
HEy @592da !
So, yeah, I know what is `alpine` linux :-D.
The bug happen because prisma2 needs `glibc` to run `migration-engine`, however this is not packaged in `alpine`.
I ended up using the `frolvlad/alpine-glibc` image which worked very well for me.

**Comment by olup** [comment]
I don't know if it's the same error but as I said before, the build worked with `alpine-glibc`, but does not work anymore with `preview 6.1`. Still builds with full fledged node image.

**Comment by olup** [comment]
Keeping this thread up to date I confirm that now  `preview-8` still won't run on `alpine` but it will in the image `alpine-glibc`.

**Comment by pantharshit00** [comment]
`alphine` don't ship openssl by default. If you use `node:alphine`, it will work as it will install openssl.

@steebchen currently testing out the binary workflows. He will have more insight on this one.

**Comment by steebchen** [comment]
For now, we recommend to use the normal `node` image or a specific one such as `node:10`. We're still investigating builds for alpine images.

**Comment by janpio** [comment]
So is this currently a bug at all? Or something we can't do anything about but should add it to the documentation? @steebchen @pantharshit00

**Comment by pantharshit00** [comment]
I think we can add this to the docs.

But in the end, it boils down to the fact how we chose to include a TLS/SSL lib in the binaries which is a broader topic.

**Comment by janpio** [comment]
Can you create a new docs issue (that boils down this discussion here to what actually needs to be added/changed) and close this one? Thanks.

**Comment by steebchen** [comment]
@janpio still investigating. It seems this is both a binary and a documentation issue – meaning we would need to provide a fixed binary and the user would have to install openssl. However, we're not there yet.

Also, should we maybe rename this issue something like "crashes when running on node:alpine image"?

**Comment by janpio** [comment]
Thanks for the clarification.

I updated the title and also assigned this to you, so you can keep track of it.

**Comment by steebchen** [comment]
Quick update: it's harder to get the alpine binary to work than initially anticipated. We recommend everyone to use the normal `node` images instead of alpine.

**Comment by shoaibsharif** [comment]
I still have the problem but I don't know if mine is the same problem or not. I am using `preview-13.2`
```sh
Error: Get config /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0: 1: /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0: ELF: not found
/usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0: 2: /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0: Syntax error: ")" unexpected
ERROR: Service 'app' failed to build: The command '/bin/sh -c prisma2 generate' returned a non-zero code: 1
```

**Comment by janpio** [comment]
Your problem looks different to me @shoaibsharif - best create a new issue and provide all information how you installed, what you are running etc.

**Comment by LongLiveCHIEF** [comment]
I've gotten this error in the last day,with _every_ node image, including `latest`, `stretch`, `alpine`, and `buster`

**Comment by LongLiveCHIEF** [comment]
```
prisma2 generate --save "init"
Error: Error: Command failed with exit code 2 (ENOENT): /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 cli --dmmf
spawn /usr/local/lib/node_modules/prisma2/query-engine-linux-glibc-libssl1.1.0 ENOENT
 ✘  ~/code/games-tracker   setup-stack ●  docker run -it --rm --entrypoint bash prisma2
root@716c9e57d5f6:/# openssl version -a
OpenSSL 1.1.0l  10 Sep 2019
built on: reproducible build, date unspecified
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/lib/ssl\"" -DENGINESDIR="\"/usr/lib/x86_64-linux-gnu/engines-1.1\"" 
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
root@716c9e57d5f6:/# uname -a
Linux 716c9e57d5f6 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux
root@716c9e57d5f6:/# uname -a
Linux 716c9e57d5f6 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux
root@716c9e57d5f6:/# 
```

**Comment by pantharshit00** [comment]
@LongLiveCHIEF Can you please paste your Dockerfile here?

**Comment by LongLiveCHIEF** [comment]
@pantharshit00 I figured out what causes this, at least in my builds. So here's what happened. 

Dockerfile:
```
ARG DISTRO_TAG=latest
FROM node:${DISTRO_TAG}

RUN npm install --global --unsafe-perm prisma2

ENTRYPOOINT ["prisma2"]
```

I then tried each of the following:

```
docker build -t prisma2 .
docker build --build-arg DISTRO_TAG=buster -t prisma2 .
docker build --build-art DISTRO_TAG=stretch -t prisma2 .
```
At first, i didn't notice it, but what happened is that each time the postinstall script failed to finish installing the query engine or migration binary, but didn't throw an exit, so the `npm install` showed as completed successfully.

However, the binary itself was actually 0% downloaded, and was basically an empty file on the system.

The `npm generate` script _does_ locate the file, but since it didn't finish downloading, the execute bit is never added, which causes an `ENOENT permission denied` error, no matter what user is trying to execute the binary.

I believe this is related to https://github.com/prisma/prisma2/issues/834, because I am unable to reach the download locations for binaries for the query engine/migration engine/format engine from my development platform.

I believe this issue should be verified as the cause by OP, in which case we can close this in favor of https://github.com/prisma/prisma2/issues/834. @592da @olup can either of you verify that you saw messages about `incorrect headers` being sent during install of prisma2 cli?

Alternatively, you can check the directory of the query-engine binary that is shown in your error, and can run `ls -al` to see if the permissions of the binary don't include an `x` (for execute), and you should also find that there is a `.partial` binary download file. 

If so, then that would confirm that this is a manifestation of https://github.com/prisma/prisma2/issues/834

**Comment by LongLiveCHIEF** [comment]
also, seems to be another one that would be fixed by the plans for https://github.com/prisma/prisma2/issues/938

**Comment by olup** [comment]
Sorry, @LongLiveCHIEF I didn't get any error about headers, I do have executable rights on `query-engine-linux-glibc-libssl1.1.0` and no `.partial` in the folder.

the binary appears with `ls` however trying to start it, even from sh, returns file not found.

**Comment by olup** [comment]
The situation is still the same : prisma 2 uses glibc and this is not included in linux `alpine`. Installing glibc by hand still conflicts with libssl. 

I have no idea why, but I reapeat that things seems to still work quite ok with the `frolvlad/alpine-glibc` image, which packages glibc on alpine. I then install node on top of that and get a quite acceptably small image (`apk add nodejs npm`). With this image, prisma2 works fne, and that is a good enough workaround for me until the prisma team have binaries compiles for `musl libc` that is included in `alpine` linux

**Comment by steebchen** [comment]
@olup is right, the issue with alpine is known, and we currently do not provide alpine binaries. We plan to do so in the future. @LongLiveCHIEF Can you please create a new issue with your problem as this seems not specific to alpine.

**Comment by tvvignesh** [comment]
I faced the same issue today. While switching to node solves this issue for now, it would be great to have an idea on how to get it running for alpine since with increase in number of containers running in GKE, switching away from alpine increases costs and possible vulnerabilites.

My original Dockerfile below.
```
FROM node:13.3.0-alpine
RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/*
RUN mkdir -p /app/server
WORKDIR /app/server
RUN echo $POSTGRES_URL
RUN npm i -g --unsafe-perm prisma2@latest
COPY creds /app/server/creds
COPY tsconfig.json /app/server/tsconfig.json
COPY ./apidoc.yaml /app/server/apidoc.yaml
COPY ./skaffold.yaml /app/server/skaffold.yaml
COPY package.json /app/server/package.json
RUN npm install
COPY src /app/server/src
RUN npm run-script build
EXPOSE 2020
CMD [ "npm", "start" ]
```

I got issue with openssl when running in alpine.

It works when I switch the Dockerfile to this with node base image:
```
FROM node:13.3.0
# RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/*
RUN mkdir -p /app/server
WORKDIR /app/server
RUN echo $POSTGRES_URL
RUN npm i -g --unsafe-perm prisma2@latest
COPY creds /app/server/creds
COPY tsconfig.json /app/server/tsconfig.json
COPY ./apidoc.yaml /app/server/apidoc.yaml
COPY ./skaffold.yaml /app/server/skaffold.yaml
COPY package.json /app/server/package.json
RUN npm install
COPY src /app/server/src
RUN npm run-script build
WORKDIR /app/server/db/prisma
RUN prisma2 lift up
EXPOSE 2020
CMD [ "npm", "start" ]
```

**Comment by steebchen** [comment]
We're aware that Alpine is not supported yet, and we're tracking this feature in https://github.com/prisma/prisma2/issues/702. Please follow this issue for updates.

I'll close this in favor of the feature request.

In the meanwhile, we recommend to use non-alpine images, e.g. `node:12` instead of `node:alpine-12`.

**Comment by ArunDhwaj** [comment]
Issue I faced, and how its resolved
===========================
1) Issues:
========
electron-quick-start/node_modules/.bin/electron ENOENT 	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19) 	at onErrorNT (internal/child_process.js:456:16) 	at processTicksAndRejections (internal/process/task_queues.j

2) Solution:
=========
Its resolved by: `$ npm install`  in root directory.

**Comment by mohamedGamalAbuGalala** [comment]
Fixed in [prisma/prisma#702 comment](https://github.com/prisma/prisma/issues/702#issuecomment-624551803)

Now you can run prisma with `node:alpine` by installing `@prisma/cli@alpha`

**Comment by pantharshit00** [comment]
@mohamedGamalAbuGalala Please use `@prisma/cli@dev` now for unstable channel. Alpha channel has been retired now.

Also, the alpine change is available in the latest stable version so I will recommend using that `npm install @prisma/cli@latest`

**Comment by mohamedGamalAbuGalala** [comment]
> @mohamedGamalAbuGalala Please use `@prisma/cli@dev` now for unstable channel. Alpha channel has been retired now.
> 
> Also, the alpine change is available in the latest stable version so I will recommend using that `npm install @prisma/cli@latest`

@pantharshit00 

Its weird for me but I got an error tells that I can't use `where` on `select` method after running migration with either (`cli@dev`, `cli@latest`) but it works with `cli@alpha`

![image](https://user-images.githubusercontent.com/14947957/87420770-23a65d00-c5d6-11ea-9f1f-2f91a081a986.png)

**Comment by pantharshit00** [comment]
@mohamedGamalAbuGalala I can't tell by just that screenshot, please open a new issue with a proper reproduction

**Comment by mohamedGamalAbuGalala** [comment]
> @mohamedGamalAbuGalala I can't tell by just that screenshot, please open a new issue with a proper reproduction

I tried to reproduce that same bug in a small project but I couldn't, and after some digging I found that my image was caching old code but still the error was weird.
