### ISSUE TITLE
Correct the description

### ISSUE THREAD

**Issue by gHashTag** [prisma/photonjs#174]
Correct the description. You have errors everywhere in the description of the photon everywhere prisma
https://github.com/prisma/photonjs/tree/master/examples/javascript/graphql-subscriptions

 ```context.prisma.createComment```

<img width="1440" alt="Screenshot 2019-08-04 at 11 23 16" src="https://user-images.githubusercontent.com/6774813/62421436-5d72a200-b6aa-11e9-996f-a04ef8c0c95f.png">

**Comment by nikolasburk** [comment]
Hey @gHashTag, thanks a lot for opening this issue. Could you please clarify what exactly you mean with `in the description of the photon everywhere prisma`. You're linking to a Photon example project, but I don't quite understand the context of that link or the screenshot you provided. Thanks!

**Comment by gHashTag** [comment]
[This example](https://github.com/prisma/photonjs/tree/master/examples/javascript/graphql-auth)
1. There is no ./prisma/datamodel.prisma file and instead schema.prisma with the new syntax. It’s no longer clear where to write.

Description
<img width="922" alt="Screenshot 2019-08-28 at 21 15 42" src="https://user-images.githubusercontent.com/6774813/63881647-ff9b5680-c9d8-11e9-8d43-89b91c60a945.png">

Fact
<img width="604" alt="Screenshot 2019-08-28 at 21 16 09" src="https://user-images.githubusercontent.com/6774813/63881677-104bcc80-c9d9-11e9-8438-60971198d4c9.png">

2. In the section Adding an operation and updating the datamodel, Prisma is called, not photon. Is that right? 
```return context.prisma.createComment({
 return context.prisma.user({ id }).comments()
 return context.prisma.post({ id }).comments()
 return context.prisma.comment({ id }).writtenBy()
 return context.prisma.comment({ id }).post()
```

Description:
<img width="943" alt="Screenshot 2019-08-28 at 21 17 53" src="https://user-images.githubusercontent.com/6774813/63881842-5b65df80-c9d9-11e9-9c93-0ec2f2913dd2.png">

May need to call photon, not prisma?

`return context.photon...`

Please correct, otherwise I can not understand the photon

**Comment by gHashTag** [comment]
@nikolasburk @schickling is there any news on my issue?

**Comment by nikolasburk** [comment]
Hey @gHashTag, thanks for the clarification and sorry for the confusion! We're actually maintaining all Photon.js example [here](https://github.com/prisma/prisma-examples/tree/prisma2) now. We needed to keep the examples around in this repo temporarily as well due to some other dependencies but then forgot the cleanup. 

In the new example home, the README has been cleaned up too to remove the misleading instructions.
