### ISSUE TITLE
notIn throws type error with empty array

### ISSUE THREAD

**Issue by artemzakharov** [prisma/photonjs#180]
I'm trying to do a simple query that looks like this:

```
  const foos = [ {...}, {...}, ... ];

  const bars = await db.bars.findMany({
    where: {
      id: {
        notIn: foos.map(foo=> foo.id)
      }
    },
    ...
```

What I've found is that if `foos` happens to be empty, and the `notIn` field thus receives an empty array to filter against, I get this error:

```
Argument notIn: Got invalid value [] on photon.findManyFoos. Provided List<>, expected List<String>.
```

Doesn't seem intentional.

**Comment by pantharshit00** [comment]
I can confirm this. Seems to be an issue with the typing

**Comment by timsuchanek** [comment]
You can check out the fix in the latest alpha with `npm install -g prisma2@alpha`.

**Comment by artemzakharov** [comment]
Can't quite yet as I'm still stuck behind https://github.com/prisma/lift/issues/99 (which affects Photon too afaik), but will try it out when I can 👍

**Comment by artemzakharov** [comment]
I'm getting the following error now:
```
Invalid photon.() invocation in ...
Reason: Error occurred during query validation & transformation:
Query (object)
  ↳ findManyFoo (field)
    ↳ where (argument)
      ↳ FooWhereInput (object)
        ↳ id_notIn (field)
          ↳ Field does not exist on enclosing type.
```
Typescript does not show any pre-emptive errors or warnings, this error triggers only when the code is invoked.
