### ISSUE TITLE
__internal is ignored

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#181]
Photon has an `__internal` constructor argument meant to be used by projects like Studio. This is ignored right now (after `platforms` feature was introduced). 

Reproduction: https://github.com/divyenduz/p2_181

### To Reproduce

1. Clone the repo and run `yarn`
2. `yarn lift save --name init`
3. `yarn prisma2 lift up`
4. `yarn prisma2 generate`
5. `yarn seed`

It works and shows inserted data in log. It should not work though because in `script.ts` we are overriding the `binaryPath` and provide a linux binary. It should have failed.

**Comment by divyenduz** [comment]
Labelling this as a bug right now because Studio uses it.

**Comment by timsuchanek** [comment]
Note: Also update the spec when done.

**Comment by timsuchanek** [comment]
![image](https://user-images.githubusercontent.com/1094804/62856060-26c50900-bcf4-11e9-95ea-b51f537f76ac.png)

`__internal` works as intended. Please note that in the CLI output, we warn you, that we couldn't find the provided binary path, but resolved to one that we found anyways.
The error message for this use-case could be a bit more clearer, but as this is an internal api that no-one else uses, this is not urgent.
