### ISSUE TITLE
Wrong type on relation include result

### ISSUE THREAD

**Issue by olup** [prisma/photonjs#182]
Hey,
Still the greatest project on the JS planet !

Small bug : when querying for a model, let's say `boy` that have a non necessary relationship with another one (like, let's say `girl`) when can query with 
```
await photon.boys.findOne({
          where : { id : "BLABLABLA"},
          include: { girl: true }
});
```

the non-necessary relation is made clear in the project.prima : 
```
girl : Girl?
```

The result type will be a single object of type `Boy` that will have a `girl` key of type `Girl`. However the type of this key should probably be `Girl | null` because the relation can exist... or not.

ATM, typescript does not catch those small potential errors and I have become so lazy with typescript that I feel frustrated that runtime errors can still happen.

Keep up rocking in the free world !

**Comment by pantharshit00** [comment]
I can confirm this behaviour. Thanks for reporting!

**Comment by timsuchanek** [comment]
This will be considered in https://github.com/prisma/photonjs/issues/167

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
