### ISSUE TITLE
"Field does not exist on enclosing type" when using notIn

### ISSUE THREAD

**Issue by artemzakharov** [prisma/photonjs#190]
I'm trying to do a query like this:

```
  const foos = [ {...}, {...}, ... ];

  const otherFoos = await db.foos.findMany({
    where: {
      id: {
        notIn: foos.map(foo=> foo.id)
      }
    },
```
this results in the following error:
```
Invalid photon.() invocation in ...

Reason: Error occurred during query validation & transformation:
Query (object)
  ↳ findManyFoo (field)
    ↳ where (argument)
      ↳ FooWhereInput (object)
        ↳ id_notIn (field)
          ↳ Field does not exist on enclosing type.
```
Typescript does not show any pre-emptive errors or warnings, this error triggers only when the code is invoked.

**Comment by pantharshit00** [comment]
I can confirm this issue.

Reproduction: https://github.com/harshit-test-org/prisma-photon-190

The `in` field works fine but the `notIn` is not properly being validated by photon runtime.

**Comment by luhagel** [comment]
Same deal with `some` from what it seems

**Comment by timsuchanek** [comment]
Thanks a lot for reporting! Fix in latest alpha.
