### ISSUE TITLE
[Question] How to generate graphql-schema file from schema.prisma

### ISSUE THREAD

**Issue by ralvs** [prisma/photonjs#192]
At prisma v1, adding the follow code to prisma.yml makes it create a graphql-schema file ready to be used on a graphql server like Yoga.

    generate:
      - generator: graphql-schema
        output: ./generated/prisma.graphql

How to do that with prisma2 ?

**Comment by pantharshit00** [comment]
Hi @ralvs 

Prisma 2 is just an ORM. It is doesn't provide a GraphQL API unlike Prisma 1. You can surely generate a GraphQL API on top of Prisma 2 using nexus-prisma(see https://nexus.js.org/docs/database-access-with-prisma-v2) or a custom-written generator in the future.

**Comment by pantharshit00** [comment]
@ralvs All those methods are still autogenerated from the schema with correct typings.

In terms of redeclaration they are better are you don't need to redeclare the implementation as you need to do with Prisma 1 and the schema imports.

But in the future, we can also have a generator that can delegate all of this.
See https://github.com/prisma/prisma2/issues/370

**Comment by ralvs** [comment]
I made some tests and maybe I understand a little more now.

Based on the examples of `nexus-prisma` plugin.
At the example with [prisma 1](https://nexus.js.org/docs/database-access-with-prisma), we could do 

    const Query = prismaObjectType({
      name: "Query",
      // Expose all generated `Todo`-queries
      definition: (t) => t.prismaFields(["*"]),
    });

Which "imports" all queries from datamodel.prisma. Also `type Todo` is automatically imported.

In the other example, using [prisma 2](https://nexus.js.org/docs/database-access-with-prisma-v2), everything is redeclare at index.js, and that is what I'm trying to avoid.

```
// Expose the full "Query" building block
const Query = objectType({
  name: "Query",
  definition(t) {
    t.crud.findOneTodo();
    t.crud.findManyTodo();
  },
});

// Customize the "Mutation" building block
const Mutation = objectType({
  name: "Mutation",
  definition(t) {
    // Expose only the `createTodo` mutation (`updateTodo` and `deleteTodo` not exposed)
    t.crud.createTodo();

    // Add a custom `markAsDone` mutation
    t.field("markAsDone", {
      type: "Todo",
      args: { id: idArg() },
      nullable: true,
      resolve: (_, { id }, ctx) => {
        return ctx.photon.todos.updateTodo({
          where: { id },
          data: { done: true },
        });
      },
    });
  },
});

const Todo = objectType({
  name: "Todo",
  definition(t) {
    t.model.id();
    t.model.title();
    t.model.done();
  },
});
```

**Comment by pantharshit00** [comment]
@ralvs 

I think this change has already been proposed here: https://github.com/prisma/nexus-prisma/issues/339

There is also a good workaround there for now

**Comment by ralvs** [comment]
That is great, @pantharshit00 
Thanks!
