### ISSUE TITLE
Missing documentation property in DMMF.Field and DMMF.Model

### ISSUE THREAD

**Issue by MichalLytek** [prisma/photonjs#193]
My datamodel:

```prisma
/// User model comment
model User {
  /// User model field comment
  id       String  @default(cuid()) @id @unique
}
```

When I log the dmmf datamodel, I have a documentation property:

![image](https://user-images.githubusercontent.com/10618781/63210960-725f2480-c0f1-11e9-8ec4-393d4b1fc4c1.png)

![image](https://user-images.githubusercontent.com/10618781/63210979-a2a6c300-c0f1-11e9-9941-f7b855c3646c.png)

But it is missing in typedefs:

![image](https://user-images.githubusercontent.com/10618781/63210984-aa666780-c0f1-11e9-90e7-5ee0e9aea1b4.png)

![image](https://user-images.githubusercontent.com/10618781/63210966-8145d700-c0f1-11e9-857d-2c6101b8dcf3.png)

**Comment by timsuchanek** [comment]
This is fixed in the latest alpha.
