### ISSUE TITLE
Implement containsInsensitive filter

### ISSUE THREAD

**Issue by Glup3** [prisma/photonjs#199]
I have a search where I filter with `contains` in the where clause, but the results are not what I was expecting. Is there a way to tweak contains, for example case insensitive?

Method:

```javascript
    t.list.field('searchExercise', {
      type: 'Exercise',
      args: {
        searchString: stringArg({ nullable: true }),
      },
      resolve: (parent, { searchString }, ctx) => {
        return ctx.photon.exercises.findMany({
          where: {
            title: {
              contains: searchString,
            },
          },
        });
      },
    });
```

Results:

![image](https://user-images.githubusercontent.com/25965213/63427163-c9783880-c414-11e9-91e8-bd5fa95a7366.png)

![image](https://user-images.githubusercontent.com/25965213/63427180-d563fa80-c414-11e9-8523-b0c564b07569.png)

![image](https://user-images.githubusercontent.com/25965213/63427213-ec0a5180-c414-11e9-96e5-de2788407312.png)

![image](https://user-images.githubusercontent.com/25965213/63427197-e01e8f80-c414-11e9-91c2-1ab202094a6f.png)

**Comment by pantharshit00** [comment]
I can confirm this behaviour but this is expected.

What you are trying to achieve will be provided by `containsInsensitive` filter which is part of the photonjs spec: https://github.com/prisma/specs/tree/master/photonjs#basic-queries

![image](https://user-images.githubusercontent.com/22195362/63773303-86c4cd80-c8f8-11e9-8f6f-3ffd9b84d7bd.png)


It is not implemented yet so I am marking this as a feature request.

**Comment by pantharshit00** [comment]
Closing in favour of #343
