### ISSUE TITLE
TypeError: cb.apply is not a function

### ISSUE THREAD

**Issue by matthewmueller** [prisma/photonjs#20]
For some reason this copy breaks:

https://github.com/prisma/photon-js/blob/9507d5219ff2729a0a41cb3eef64382ec4d609c0/packages/photon/src/generation/generateClient.ts#L125

My guess is that when typescript compiles async/await into yield statements, fs-extra doesn't properly handle it.

Workaround (in transpiles code):

```
    yield fs_extra_1.default.copy(
      path_1.default.join(__dirname, '../../runtime'),
      path_1.default.join(outputDir, '/runtime'),
    )
```

to

```js
    fs_extra_1.default.copySync(
      path_1.default.join(__dirname, '../../runtime'),
      path_1.default.join(outputDir, '/runtime'),
    )
```

I'd suggest we use: https://github.com/sindresorhus/cpy

**Comment by Hituu** [comment]
my  node -v
v14.5.0
and  npm -v
4.6.1
if i install anything it is giving me 
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:

**Comment by Hituu** [comment]
can you tell me how can i solve this becoz everytime if i install anything it is showing me the same error

**Comment by janpio** [comment]
What are you trying to install @Hituu?

**Comment by Hituu** [comment]
> What are you trying to install @Hituu?

I am trying to install less version 2.7.2 globally

**Comment by Hituu** [comment]
Less css compiler

**Comment by janpio** [comment]
Then you are unfortunately in the totally wrong place here - we can not help you with that. Your best bet is asking in their repository or asking in the npm community.
