### ISSUE TITLE
Add pretty datamodel parser error for `get_config`

### ISSUE THREAD

**Issue by timsuchanek** [prisma/photonjs#200]
As of now, `query-engine cli --dmmf` prints beautiful datamodel parser errors to `stderr`.
It would be awesome to have the same for `query-engine cli --get_config`.

**Comment by janpio** [comment]
@schickling via Slack:

> this should be in the SDK repo

**Comment by mavilein** [comment]
This is done from our side. @timsuchanek needs to validate whether this works.

**Comment by janpio** [comment]
Did @timsuchanek validate?
