### ISSUE TITLE
Usage of PostGIS PostgreSQL extension along with Prisma

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/photonjs#210]
I need to use PostGIS extension. When I create DB, I install the extension. But then, after the installation, I execute Prisma Lift. Looks like Prisma Lift removes all the tables, which are not needed according to Prisma file. So, it tries to remove spatial_ref_sys, for example. Prisma can't remove this table, because it is used by PostGIS extension. Thus, Prisma Lift fails. What can I do to allow usage of PostGIS?

**Comment by janpio** [comment]
There is an issue about this at https://github.com/prisma/lift/issues/76. 
It also includes a workaround: https://github.com/prisma/lift/issues/76#issuecomment-516104732
