### ISSUE TITLE
Nested reads

### ISSUE THREAD

**Issue by iherger** [prisma/photonjs#218]
I just discovered nested reads in #70 

From my point of view, nested reads (using `select` and/or `include`) is actually really nice and very powerful.

I don't think this sufficiently described in the documentation, so I would suggest to add a paragraph about nested reads, e.g. in https://github.com/prisma/prisma2/blob/master/docs/relations.md#relations-in-the-generated-Photon-API

**Comment by ManAnRuck** [comment]
it would be also good for **Nested Writes** 🙏🏼

**Comment by nikolasburk** [comment]
Thanks for opening this issue @iherger 🙌 [I've added some more docs around nested reads and writes](https://github.com/prisma/prisma2/pull/581) (cc @ManAnRuck). 

Note that the Photon.js will see some major updates soon (more info in the [spec](https://github.com/prisma/specs/tree/master/photonjs)), so I'm sparing the work of going too deep into the documentation right now. The next version of the Photon.js API will be documented very thoroughly.
