### ISSUE TITLE
Detect images by OS and Linux distribution instead of by platform

### ISSUE THREAD

**Issue by steebchen** [prisma/photonjs#221]
Currently, this is blocked by prisma/prisma-engine#37. After this is done, the detection needs to be refactored.

Instead of just checking the libssl version or platform type, we should check for the operating system and the core distribution like CentOS, Debian, etc. and additionally append the libssl version and download the correct binary.

Idea: if no specific platform for which we have built binaries is detected, I think we should still check the OpenSSL version and default to Debian (maybe log a warning message), because it seems Debian works on most other distributions.

More info at prisma/prisma-engine#37 (binary issue) and prisma/prisma2#533 (umbrella issue)

**Comment by janpio** [comment]
Relevant code:
https://github.com/prisma/photonjs/blob/master/packages/get-platform/src/getPlatform.ts
https://github.com/prisma/photonjs/blob/master/packages/get-platform/src/platforms.ts

**Comment by pantharshit00** [comment]
I am going to mark this as a feature since it is caused by a query engine refactoring.
