### ISSUE TITLE
Regenerating Photon causes API in development to crash

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#234]
With a `postinstall` hook, `prisma generate` runs on all `yarn add` operations, this causes an API in development with hot reload to fail for a few moments when the generation is happening as it cleans the `node_modules` up. 

Related issue: https://github.com/prisma/photonjs/issues/88

More on this context: 
![image](https://user-images.githubusercontent.com/746482/65499149-76831c80-debd-11e9-8fea-ea69d7fb9a11.png)

**Comment by momakes** [comment]
I was using `ts-node-dev` at the time and it totally crashed (had to re-run.)
Now switched to Babel + Nodemon, the same thing happens and I have to re-run.

![CleanShot 2019-09-24 at 12 59 32](https://user-images.githubusercontent.com/55196141/65500053-843f9e80-decb-11e9-948f-bd6302d6b5ff.png)

**Comment by divyenduz** [comment]
A potential solution to this could be to generate photon into a temporary directory and then swapping that in the main directory atomically using symlink. 

Problems with this approach (not-exhaustive): 

1. Might not work on windows 
2. Might not be registered as a change by editors (for auto-completion etc)

**Comment by divyenduz** [comment]
Reproduction: https://github.com/divyendu-test/photonjs-234

GIF of reproduction: https://divyendu.s3-eu-west-1.amazonaws.com/photonjs-234-2.gif

The solution I proposed earlier won't work as this is happening while yarn pruning and not `prisma2 generate`.

**Comment by timsuchanek** [comment]
This has been fixed by introducing the facade package 🎉
