### ISSUE TITLE
Query parallelism

### ISSUE THREAD

**Issue by nlarusstone** [prisma/photonjs#236]
Following on from the discussion in #153, I wanted to make a separate issue to track the status here.

@timsuchanek said:
`Parallelization in the Rust query engine: This one is of far higher importance, as of now the query engine can only execute one query at a time.`

I would agree with that statement, as being limited to one query at a time is a deal breaker for using this in anything other than a fun side project.

As we're hoping to use prisma2 in some of our upcoming workflows, it would be great if we could get a status update on the parallelism and maybe a rough roadmap/timeline of when this is expected to get solved.

Thanks so much!

**Comment by divyenduz** [comment]
Thanks for raising this, I am closing this in favor of https://github.com/prisma/prisma2/issues/420

It is a duplicate, please ping me if you think that this issue should also exist. 

This is high on our priority list, we will get to it soon.
