### ISSUE TITLE
Photon filters `in` prop missing `null` support

### ISSUE THREAD

**Issue by MichalLytek** [prisma/photonjs#242]
The Photon find filters like `StringFilter` have all properties optional with null support but the `in` and `notIn` have only `Enumerable<string>` optional type: 

![image](https://user-images.githubusercontent.com/10618781/66115030-4f6ccf00-e5d0-11e9-8e01-6cb50a6749b1.png)

This conflict with generated GraphQL types based on DMMF schema:

![image](https://user-images.githubusercontent.com/10618781/66115175-94910100-e5d0-11e9-88e1-c1846f4d6f6e.png)

This apply to all `Enumerable` usage in Photon generated types:

![image](https://user-images.githubusercontent.com/10618781/66115258-c3a77280-e5d0-11e9-986d-2ba02f970a0d.png)

It's a really big blocking problem for the integration of Prisma2 and GraphQL when we want to pass the nullable args to the photon query.

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
