### ISSUE TITLE
findOne: Stop throwing an error when no record found 

### ISSUE THREAD

**Issue by schickling** [prisma/photonjs#245]
Even though we're currently working on some bigger API changes which will fix this behavior, it will take a little while until all these changes will be implemented and ship. In the meanwhile I'd like to address one of the most frequent points of feedback by Prisma 2 testers which is to stop throwing an error when no record was found when using the `findOne` operation. (See #89)

@timsuchanek would be great if you could address this during the current sprint 🙏

**Comment by danlannz** [comment]
@timsuchanek @schickling was this reverted in Preview 16? I'm getting the following error in my seed script but Preview 15 works as expected

```
  106 for (const [modelName, models] of Object.entries(data)) {
  107   for (const entity of models) {
  108     const existingEntity = await (photon as any)[modelName]
→ 109       .findOne(

Reason: Error occurred during query execution:
ConnectorError(RecordDoesNotExist)
```

**Comment by yovanoc** [comment]
Yes same for me, regression I supposed :/

**Comment by pantharshit00** [comment]
I can confirm this regression.

**Comment by pantharshit00** [comment]
![image](https://user-images.githubusercontent.com/22195362/68580075-98e7ee00-049b-11ea-9ef0-a95ad266fcdd.png)

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma2/issues/914 which we are using to track the regression in our milestone

**Comment by tvvignesh** [comment]
Still facing similar issue. Added details here: https://github.com/prisma/prisma2/issues/914#issuecomment-566062290
