### ISSUE TITLE
`.count()` returns `null` for empty tables

### ISSUE THREAD

**Issue by madebysid** [prisma/photonjs#253]
To reproduce:

1. Create a blank project with `prisma2 init`
2. Without seeding the database, create a script with these contents:
```ts
import { Photon } from "@generated/photon";

const photon = new Photon();
async function main() {
  console.log(await photon.users.count());
}

main()
```

3. The query logs `null` instead of 0

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.
