### ISSUE TITLE
Need to call `photon.disconnect()` to make script terminate

### ISSUE THREAD

**Issue by nikolasburk** [prisma/photonjs#255]
I have the following simple TypeScript script based on Photon.js:

```
import { Photon } from '@generated/photon'

const photon = new Photon()

async function main() {
  const people = await photon.people.findMany({
    first: 20
  })
  console.log(people)

  // await photon.disconnect()
}

main()
``` 

When not including the `photon.disconnect()` call, my script won't terminate. Is that the expected behavior or should Photon.js autoclose the DB connection?

**Comment by pantharshit00** [comment]
I can confirm this behaviour but still, I don't know the expected behaviour.

cc @timsuchanek

**Comment by divyenduz** [comment]
I can confirm this too. Adding it as a candidate to know if it is expected behavior or a bug.

**Comment by timsuchanek** [comment]
This is definitely expected. Photon is opening a database connection, that is keeping the process alive.

We can separately discuss if we, first of all, want this behavior (that's also the case for any other db client) and if we don't want it, we could investigate how to find out, if the db connection is the "last pending microtask" in the current node process.

That sounds like a bit of magic is needed, but could potentially be feasible.
