### ISSUE TITLE
Select in finds methods optional fields

### ISSUE THREAD

**Issue by yovanoc** [prisma/photonjs#256]
Hello, when I select an optional field in my database like that:

```ts
select: {
              id: true,
              username: true,
              data: {
                select: {
                  accountId: true
                }
              }
            }
```

where the model is :

```
type CUID = String @id @default(cuid())

model AccountConfiguration {
  id                          CUID
  username           String                       @unique
  data                     AccountData?
```

then typescript definition don't tell that it can be optional (null or undefined)

![image](https://user-images.githubusercontent.com/7302317/66466660-5fc6f300-ea83-11e9-8c14-b69a3c959d1d.png)

It should be `{ accountId: number; } | undefined`

Thanks

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.

**Comment by yovanoc** [comment]
Doesn't work for me on alpha 241, you tested it on a findOne?

**Comment by yovanoc** [comment]
Oh is working in 242, but I have a question why for an Array type it can be `| null` return just an empty array is better because now we have to check if its not null to iterate...
