### ISSUE TITLE
`count` queries do not invoke `beforeRequest` hook

### ISSUE THREAD

**Issue by madebysid** [prisma/photonjs#258]
The `beforeRequest` hook that Studio configures for requests is not called for a query like so: `photon.users.count()`

**Comment by janpio** [comment]
Please confirm and reproduce @pantharshit00

**Comment by madebysid** [comment]
Since this is an internal thing and definitely not to be used by others, it isn't documented. Here's how I'm using it in Studio:

When initializing Photon, you can pass in a beforeRequest hook like so:
```
const photon = new Photon({ 
        __internal: {
          hooks: {
            beforeRequest: args => {
                console.log('run before request', args)
            },
          }
        },
      })

await photon.users.findMany({})
```

**Comment by pantharshit00** [comment]
I am unable to reproduce this with `prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483`.

![image](https://user-images.githubusercontent.com/22195362/67072772-399c0400-f1a3-11e9-9bcf-c5bb9a528942.png)

**Comment by madebysid** [comment]
I can't reproduce this anymore either. There must be something wrong with the way I handle count queries then. Closing, noop.
