### ISSUE TITLE
DateTime not converted to Date when using `where`

### ISSUE THREAD

**Issue by MichalLytek** [prisma/photonjs#267]
Prisma2 preview 15 introduced mapping of `DateTime` to JS `Date`:
```ts
  console.log(result1[0].posts);
  const result2 = await photon.users.findMany({
    select: {
      id: true,
      posts: { last: 1 },
    },
  });
  console.log(result2[0].posts);
```
![image](https://user-images.githubusercontent.com/10618781/67485767-f9d59080-f66a-11e9-9905-3a72b071307c.png)

But when using the `where` option in find, I receive the date as a string which breaks my API:
```ts
  const result1 = await photon.users.findMany({
    where: {
      id: { in: ["ck24ojnxx000360da79ze73gb", "ck24ojnxl000060damtkztmqs"] },
    },
    select: {
      id: true,
      posts: { last: 1 },
    },
  });
  console.log(result1[0].posts);
```

![image](https://user-images.githubusercontent.com/10618781/67485808-11147e00-f66b-11e9-93bc-7a108668b2f4.png)

**Comment by timsuchanek** [comment]
Fixed in latest alpha.
You can try it out with `npm i -g prisma2@alpha`.
