### ISSUE TITLE
Multiple calls to disconnect should be noops

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/photonjs#281]
#### Problem

Reported by user here https://github.com/prisma-labs/nexus-prisma/issues/340#issuecomment-547662106. 

It seems that it is an error to call disconnect if photon is already in a disconnected state. 

#### Solution Proposal

Maybe it should be a warning? 
Maybe it should be a noop? 
Maybe it should be a noop but upgraded to a warning if a "strict" mode is enabled? 

```
new Photon({ strict: true, ... })
```

#### Notes

Labeling this as `improvement` under assumption we would take the simple `noop` approach. Change accordingly.

**Comment by timsuchanek** [comment]
Just tried calling multiple `.disconnect()` calls - that works.
The problem that occurs in https://github.com/prisma-labs/nexus-prisma/issues/340
is a different one: When the engine has already been stopped, a *Request* fails.

I improved the error message there a bit to help in the future.
