### ISSUE TITLE
[Suggestion] Log SQL queries in debug mode

### ISSUE THREAD

**Issue by sameoldmadness** [prisma/photonjs#282]
At the moment if I want to know which SQL statements Photon is executing I need to enable query log on a database side.

It would be nice to have the option to log SQL statements on Photon's side.

**Comment by sameoldmadness** [comment]
It can be `--verbose` flag. Or even `--log-sql-queries`.

**Comment by pantharshit00** [comment]
Hi again,

This is already in the works. Since this was already reported, I need to close this one as a duplicate of https://github.com/prisma/prisma2/issues/388
