### ISSUE TITLE
UniqueConstraintViolation error data as JSON object

### ISSUE THREAD

**Issue by vadim-shilov** [prisma/photonjs#293]
Hello!
Do you have any plans to support returning the UniqueConstraintViolation error data as JSON object which contains the name of the field with duplicate value? At this moment this info is returned as a string which I need to parse.

**Comment by janpio** [comment]
Internal Note: Error spec covers this

**Comment by tomhoule** [comment]
This is resolved in preview 18 (which should be released very very soon).
