### ISSUE TITLE
Support for schemas (Postgres Oracle etc.)

### ISSUE THREAD

**Issue by vanthome** [prisma/photonjs#301]
Hello, great tool! Do you plan to support DB schemas as they exist in PostgreSQL for example?
BG

**Comment by janpio** [comment]
What do you mean exactly @vanthome - if we want to support existing databases that already have a schema? Then yes, we have an "Introspection" step that can be used to create a Prisma schema file from an existing database (currently MySQL, Postgres or SQLite) that then can be used to generate Photon.

Or did I misunderstand?

**Comment by pantharshit00** [comment]
Here you can find docs on introspection: https://github.com/prisma/prisma2/blob/128be311af1a6e0fc47dd4d54e744a5042c43fb7/docs/introspection.md

**Comment by vanthome** [comment]
Yes, you misunderstood. I'm not referring to the entirety of tables and other objects. I know the term is ambiguous and that's why I mentioned Postgres and Oracle. Please see here what a schema in Postgres is:

https://www.postgresql.org/docs/current/ddl-schemas.html

**Comment by pantharshit00** [comment]
Oh, we do support Postgres schemas. We ask about them in our cli init flow: 
![image](https://user-images.githubusercontent.com/22195362/69413257-79bc4c80-0d36-11ea-8ab0-6bc14f406dd0.png)

Or you can add it to connection string like so:
![image](https://user-images.githubusercontent.com/22195362/69413286-880a6880-0d36-11ea-96a2-e18918a66d8b.png)

Also, we don't currently support oracle. We support SQLite, MySQL and PostgreSQL

**Comment by janpio** [comment]
Sorry I didn't get your question in the first try, seemed to obvious to me as we really do support this for quite some time. 

Does that answer you question @vanthome?
Or are there any aspects that @pantharshit00 did not touch on?

**Comment by vanthome** [comment]
@janpio well kind of but I would assume you only support one schema at a time and not switching schemas at runtime, right?

**Comment by pantharshit00** [comment]
Yes, we don't support querying across multiple schemas right now. Maybe you can open a new issue for that titled "Support for multiple schemas".

**Comment by pantharshit00** [comment]
Closing in favour of https://github.com/prisma/prisma2/issues/1122
