### ISSUE TITLE
Order by related fields

### ISSUE THREAD

**Issue by alan345** [prisma/photonjs#303]
Example: a User has many Posts. Should be possible to order the Posts by User name.

Maybe:
```
query {
  allPosts(orderByRelated: [user_name_ASC]) {
    id
  }
}
```

related to this issue with Prisma1: https://github.com/prisma/prisma/issues/95

**Comment by glen-84** [comment]
Duplicate of #108.

**Comment by pantharshit00** [comment]
Hi,

Thanks for reporting this! It has already been reported before, so I am going to close this as a duplicate of #108 

Also, thanks to @glen-84 for pointing out the related issue
