### ISSUE TITLE
Cannot fetch DateTime lists

### ISSUE THREAD

**Issue by madebysid** [prisma/photonjs#311]
Steps to reproduce:

1. Create a new Blank project with SQLite
2. Use this schema:
```
generator photon {
  provider = "photonjs"
}

datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
}

model User {
  id           String     @default(cuid()) @id
  datetime     DateTime
  datetimelist DateTime[]
}
```

3. Use this script:
```
const { Photon } = require("@generated/photon");
const photon = new Photon();

async function main() {
  await photon.users.create({
    data: {
      datetime: "2019-10-01T13:18:19.617Z",
      datetimelist: {
        set: [
          "2019-10-01T13:18:19.617Z",
          "2019-10-01T13:18:19.617Z",
          "2019-10-01T13:18:19.617Z"
        ]
      }
    }
  });
  console.log(await photon.users.findMany());
}

main()
  .catch(e => console.error(e))
  .finally(async () => {
    await photon.disconnect();
  });
```

This throws no errors, but the `datetimelist` field's value is not correctly returned from the `findMany` call. Note that a simple DateTime works as intended. Photon complains about an `Invalid Date`, even though the same date is used in both `datetime` and `datetimelist` fields.

Looking into the SQLite file, it seems the right data is created in the DB. This might very well be a photon issue, please relocate if that's the case!

**Comment by divyenduz** [comment]
Internal note: Implementation is changing, postgres will support scalar lists, for other databases using a model is expected. We are removing the scalar lists shim.

**Comment by divyenduz** [comment]
@madebysid is there anything actionable on this issue now that scalar list shim is removed?

**Comment by madebysid** [comment]
@divyenduz Agree, closing.
