### ISSUE TITLE
Is it possible to check then delete in same query?

### ISSUE THREAD

**Issue by outerlook** [prisma/photonjs#315]
Hi! :)

Would it be good to check for records before deleting a nested related request?

### My example
Schema: 1 Place may have 1 Coordinate **(1:1)**

My intentions in a mutation:

if coordinate is included in mutation to edit a place, it should update or create the existent record. If not, it should delete the existent (if it exists) record. 

I was doing this with the following photon function:

```
ctx.photon.place.update parameter:
	...args, // just to keep issue simple, there are several args
	coordinate: coordinate // check if it is undefined
		? {
				upsert: { create: coordinate, update: coordinate }
			}
		: {
				delete: true
			}
```

However, it fails if there's no coordinate and a previous record didn't exist, which will then try to delete this non existent. (I kind of interpreted that on this error)
```
Reason: Error occurred during query execution:
InterpretationError("Error for binding \'6\': AssertionError(\"[Query Graph] Expected a valid parent ID to be present for a nested connect on a one-to-many relation.\")")
``` 

It would be easy to first get current place with "findOne" but it would require two queries. Is it a common problem for anyone else? Should there be a explicit "deleteIfExists" or could it be handled naturally on a simple "delete" request?

Thanks in advance, and sorry if I missed something.

**Comment by outerlook** [comment]
I know the error says that's a one-to-many relationship, but there's no "[]" for arrays in either models on schema.

model Coordinate {
}

**Comment by pantharshit00** [comment]
I think you should make separate queries for this. If the relation is required we simply can't do this as we database is doing that validation.

**Comment by outerlook** [comment]
Oh, right. I didn't thought on this database side limitation. So, is it possible to inform us when that kind of situation happens on a error message?

**Comment by pantharshit00** [comment]
Yes, I agree we need to improve that error message. The error message might already improve in the next release we are currently implementing the error spec: https://github.com/prisma/specs/tree/master/errors

**Comment by aguilera51284** [comment]
i vote for deleteIfExists :)
