### ISSUE TITLE
PhotonJS fails to load environment variables from env file

### ISSUE THREAD

**Issue by THPubs** [prisma/photonjs#352]
Now we can set environment variables inside the prisma schema file as defined in here: https://github.com/prisma/prisma2/blob/master/docs/prisma-schema-file.md#using-environment-variables . When we run CLI commands, it will automatically load the values from the `.env` file. But, when we use photon js, it won't pick it up. To fix this, we have to use `dotenv` right before instantiating photon like this:

```javascript
import { Photon } from '@generated/photon'
import * as dotenv from 'dotenv';

dotenv.config(); // Load the environment variables
const photon = new Photon()
```

Now there are two ways to fix this:

- We can mention this in the documentation.
- We can call `dotenv` inside the photonjs library itself.

What do you think is the best? My vote is for the second option. I can create a PR the best choice.

**Comment by divyenduz** [comment]
Closing this in favor of https://github.com/prisma/prisma2/issues/1033

The behavior is expected and will be documented soon.
