### ISSUE TITLE
Document error consumption

### ISSUE THREAD

**Issue by lasharela** [prisma/photonjs#353]
```
        try {
          user = await ctx.photon.users.create({
            data: {
              name,
              email,
              password: hashedPassword,
            },
          })
          console.log("====", user)
          debugger
        }
        catch (error){
          throw new Error('Error during registration. Please try later')
        }
```

The email field is unique. When I'm trying to create a user with an existing email it throws the error.  Is there a way to identify specific error types that, email was duplicated? 
Or I have to check in advance if a user with these emails exists or not?

**Comment by divyenduz** [comment]
This issue is tracked generally by this issue: https://github.com/prisma/prisma2/issues/609
I am closing this one in favor of that. 

Please re-open a new issue, if it still exists once 609 is closed. 

Thanks,
