### ISSUE TITLE
Photon and undefined target="exit" error

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#357]
A lot of issues point back to the error `undefined target="exit"`, this issue tracks reproducing and fixing that. After this we need to revisit all other issues that pose this error, to validate if they are fixed or if there is an underlying error consumed in Photon/QE land. 

Reproduction: https://github.com/divyendu-test/photonjs-357

Related issues: 

https://github.com/prisma/photonjs/issues/305
https://github.com/prisma/photonjs/issues/355

**Comment by tomhoule** [comment]
I'm investigating this. The datamodel errors seem to not be handled properly. I'll try to test with a custom error handling where I make the datamodel errors more in line with the rest.

**Comment by hitochan777** [comment]
I am also facing a similar problem.
After deleting node_modules and running `npx prisma2 generate`, then I run invoked findMany. Then I got the following error.

```
Invalid `photon.()` invocation in /my_proj/post_repository.ts:161:43
    undefined target="exit" timestamp="2019-12-21T14:06:38.768Z" fields={"message":"1"}
```

**Comment by divyenduz** [comment]
For anyone who reads this: This is fixed in the latest alpha, please try it out by installing the latest alpha via `npm install prisma2@alpha && npm install @prisma/photon@alpha`.

I already tried my reproduction and it is not reproducible.

**Comment by jamesopti** [comment]
@divyenduz I can confirm that the current `@alpha` provided me a much better error message. Thanks!

**Comment by divyenduz** [comment]
This should doable via https://github.com/prisma/prisma2/issues/686
