### ISSUE TITLE
Intermittent @prisma/photon did not initialize yet

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#359]
![image](https://user-images.githubusercontent.com/746482/71098701-6f189a00-21b2-11ea-81ae-ced9300a425d.png)

I run into this intermittently for me to run `prisma2 generate` again to fix this whenever it happens. 

Raised this internally with Tim and found out that there is a related issue: https://github.com/yarnpkg/yarn/issues/7762

Persisting this information in form of this issue. I don't have a clean reproduction yet but an attempted reproduction can be to run `yarn prune` or `yarn install` twice 🤔

**Comment by pantharshit00** [comment]
Unable to reproduce with the give possible ways of reproducing.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/22195362/71186855-f265e880-22a3-11ea-8117-d6292c8fc1f8.png">

Also, yarn prune is now built in to install. You can't install twice as it would just says everything is upto date.

**Comment by divyenduz** [comment]
> You can't install twice as it would just says everything is upto date.

That was a hunch, running install twice, even when it says everything up to date. 
Base of hunch: 2nd install will prune because it is in the install, and then not install because no deps changed, which means no post install hook would run and the binaries would be removed. 

Just a hunch, did you try it?

**Comment by pantharshit00** [comment]
I tried that but I was unable to reproduce it.

**Comment by Albert-Gao** [comment]
I have the same error after deploying to AWS Lambda
I have a repo to reproduce this, I think it is due to the fact, the photon is not generated on the lambda server but the build-time? Not sure.

It is a private repo, mind if I add you? @pantharshit00

**Comment by divyenduz** [comment]
Closing this in favor of this one https://github.com/prisma/photonjs/issues/390

Which has more information.
