### ISSUE TITLE
Filtering by ENUM type

### ISSUE THREAD

**Issue by malekjaroslav** [prisma/photonjs#361]
Currently I see no option to filter by enum types and no types are generated for that. For example I want to return all bookings by status and I only want `CONFIRMED` and `PENDING`. 

This is a screenshot from Photon type definitions:
<img width="416" alt="Screenshot 2019-11-19 at 16 53 27" src="https://user-images.githubusercontent.com/7753942/69136448-741ff600-0aed-11ea-8441-47c859f3d95e.png">

**Comment by pantharshit00** [comment]
This prevents us to perform queries like these:
```prisma
enum PermissionName {
    CONTRIBUTOR
    OWNER
}

model Doc {
    id           String            @default(uuid()) @id
    name         PermissionName
}
```
```js
const doc = await photon.doc.findMany({
      where: {
        name: {
          in: ["OWNER", "CONTRIBUTOR"],
        }
      },
    })
```

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by AhmedElywa** [comment]
small issue
![image](https://user-images.githubusercontent.com/4535142/72374847-bba0b800-3713-11ea-98ef-6cb2208d3338.png)

**Comment by pantharshit00** [comment]
@AhmedElywa Can you please open a new issue about this 🙏 ?

**Comment by AhmedElywa** [comment]
@pantharshit00 It was in `2.0.0-alpha.538` i don't know if it still in last version because i can't upgrade to last version before upgrading `nexus-prisma` package

**Comment by pantharshit00** [comment]
@AhmedElywa Are you able to upgrade now? nexus-prisma has released an update that makes it compatible with the latest prisma release: https://github.com/prisma-labs/nexus-prisma/issues/579

**Comment by AhmedElywa** [comment]
it's working very good 
what i said that generated types has duplicated of type null
![image](https://user-images.githubusercontent.com/4535142/73137515-9ee47880-4061-11ea-9517-15b19f2c8e71.png)

**Comment by pantharshit00** [comment]
I went ahead and created https://github.com/prisma/prisma-client-js/issues/442 to track this, please follow that issue now 🙏
