### ISSUE TITLE
Unable to filter included relation in selection set

### ISSUE THREAD

**Issue by Fumler** [prisma/photonjs#370]
Hello.

I figure this might just be me using photon and nexus incorrectly, but in any case, any guidance here would be appreciated.

A reproduction can be found here: https://codesandbox.io/s/goofy-pond-zivnr?fontsize=14&hidenavigation=1&theme=dark

Thanks to ctrlplusb and [his great codesandbox template](https://github.com/ctrlplusb/prisma2-template/tree/master/) you should be able to run this example properly right off the bat, but you might need to open a second terminal to seed the database, just click the `+` in the bottom right window and run `yarn ts-node seed.ts`

Then in the graphql playground use this query:
```graphql
{
  event(slug: "test") {
    title
    id
    posts {
      title
      published
    }
  }
}
```

---

**The issue**:
I am trying to fetch an `event` and its `posts`, but I only want the posts which have `published: true`. So to accomplish this I thought I might be to do something like:

src/schema.ts:
```typescript
    t.field("event", {
      type: "Event",
      nullable: true,
      args: {
        slug: stringArg({ required: true }),
        first: intArg({ nullable: true }),
        skip: intArg({ nullable: true })
      },
      resolve: (_, { slug, first, skip }, ctx) => {
        return ctx.photon.events.findOne({
          where: {
            slug
          },
          include: {
            posts: {
              first,
              skip,
              where: {
                published: true
              }
            }
          }
        });
      }
    });
```

But if I run the provided query from the top of this issue, the response data is this:
```json
{
  "data": {
    "event": {
      "title": "An event title",
      "id": "ck4qaic430000yxdu1t1y62rw",
      "posts": [
        {
          "title": "I should show up",
          "published": true
        },
        {
          "title": "I should show up 2",
          "published": true
        },
        {
          "title": "I should NOT show up",
          "published": false
        },
        {
          "title": "I should NOT show up 2",
          "published": false
        },
        {
          "title": "I should NOT show up 3",
          "published": false
        }
      ]
    }
  }
}
```

**Comment by pantharshit00** [comment]
Hi,

This is not a problem in photon but in your code on how you are handling related fields. You have `t.model.posts()` on you `Event` which is telling nexus-prisma to resolve it. The data you have returned in your post resolver which is correct will be discarded for posts and tell will be returned from the data which nexus-prisma resolves inside the `t.model.posts()`.

So in order to fix this either make `Event.posts` custom, as I did here: https://codesandbox.io/s/vigilant-robinson-53zut or just turn on filtering by `t.model.posts({ filtering: true }) and pass the filter from the frontend.

**Comment by pantharshit00** [comment]
Please open a new issue in the nexus-prisma repository if you still have any concerns, photon is working as intended here: https://github.com/prisma-labs/nexus-prisma
