### ISSUE TITLE
Photon's query engine process characteristics

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#389]
A common pattern to deploy node applications is lambda. 

We want to optimize for this case "Engine has already been stopped":  
https://github.com/prisma/photonjs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Engine+has+already+been+stopped

Query Engine might stop because of the following reasons: 

1. A dangling `photon.disconnect()` call in lambda (which is notably incorrect usage but common), but the [photon's constructed object](https://github.com/prisma/prisma2/blob/master/docs/photon/deployment.md#photon-in-faas-environment-eg-aws-lambda-netlify) is reused across invocations. 

2. The query engine panics for whatever reason and a new request is received in lambda. 

Currently, photon yields the aforementioned error. 

We can however, alter this behavior to try and reconnect (even re-spawn the QE) when a request is received. 

This is a better alternative to trying and recovering the QE from crashing, where handing node's process characteristics would be difficult aka we are only optimizing for lambda (where subsequent request after a crash tries to reconnect). 

> Note that we still emit exit code 1 and crash when QE crashes, we do this to ensure that in no case, Photon should be alive and QE should be dead.

**Comment by timsuchanek** [comment]
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
