### ISSUE TITLE
The field is considered mandatory in the type definition, although in the model this field is marked optional

### ISSUE THREAD

**Issue by perevezencev** [prisma/photonjs#400]
When an optional field (for example, a name) is present in the model in type declarations, it is considered mandatory and can take the value `null`

<img width="287" alt="image" src="https://user-images.githubusercontent.com/5954104/72211303-033bff80-34da-11ea-8e16-467784a5427f.png">

<img width="222" alt="image" src="https://user-images.githubusercontent.com/5954104/72211299-eb647b80-34d9-11ea-9405-ee28a743a056.png">

**Comment by pantharshit00** [comment]
I am going to close this but feel free to post any follow ups if you feel this doesn't address your concern.

**Comment by perevezencev** [comment]
Thanks. I realized that this is the expected behavior.
