### ISSUE TITLE
@unique is not enforced with SQLite

### ISSUE THREAD

**Issue by nikolasburk** [prisma/photonjs#47]
I'm using this project file:

```groovy
datasource db {
  provider = "sqlite"
  url      = "file:my.db"
}

generator nexus_prisma {
  provider = "nexus-prisma"
  output   = "node_modules/@generated/nexus-prisma"
}

generator photon {
  provider = "photonjs"
  output   = "node_modules/@generated/photon"
}

model User {
  id    String  @default(cuid()) @id
  email String  @unique
  name  String?
  posts Post[]
}
  
model Post {
  id        String   @default(cuid()) @id
  published Boolean
  title     String
  content   String?
  author    User?
}
```

Then I'm running this script:

```
import Photon from '@generated/photon'

const photon = new Photon()

async function main() {

  await photon.connect()

  const newUser = await  photon.users.create({
    data: { 
      email: 'burk@prisma.io', 
      name: 'Nikolas'
    },
    select: { id: true }
  })
  console.log(`Create a new user with ID: ${newUser.id}`)

  photon.disconnect()
}

main().catch(e => {
  console.error(e)
  photon.disconnect()
})
```

I can run it multiple times in a row and the DB happily creates new `User` records with the same `email` not enforcing the unique constraint that I specified on the `email` field.

![image](https://user-images.githubusercontent.com/4058327/59826337-672c8a00-9336-11e9-81b5-6edb18f3aa6d.png)

**Comment by norbiu** [comment]
Same thing with MySQL:

```
datasource db {
  provider = "mysql"
  url      = "mysql://root:root@localhost:3306/test"
}

generator photon {
  provider = "photonjs"
  output   = "./generated/photon"
}

model User {
  id        String   @default(cuid()) @id @unique
  email     String   @unique
  createdAt DateTime @default(now())
  name      String?
}

```

**Comment by dpetrick** [comment]
That is most likely a migration engine / datamodel conversion issue.

**Comment by victordombrovskiy** [comment]
I can confirm this issue. Happens for me as well. I currently use SQLite.

**Comment by mavilein** [comment]
This is currently not implemented. The reason is that the current introspection implementation in the `migration-engine` is very minimal right now. It does not introspect indexes. This is the foundational piece to enable this feature.
We plan to rewrite the introspection anyway in the next days which will include this feature. Therefore i would like to not implement this in the current implementation which will be thrown away soon.

**Comment by mavilein** [comment]
I did a basic implementation which does not leverage the introspection: https://github.com/prisma/prisma/commit/987243ce27251e1c05e83b84363017054686fe17
This will be available with tomorrows preview release.

**Comment by pantharshit00** [comment]
I can confirm this has been fixed.
