### ISSUE TITLE
GraphQL method

### ISSUE THREAD

**Issue by joshhopkins** [prisma/photonjs#53]
Prisma Client's [$graphql method](https://www.prisma.io/docs/1.34/prisma-client/basic-data-access/reading-data-JAVASCRIPT-rsc2/#graphql-requests) is extremely useful. Hope to see this implemented in photonjs.

**Comment by matthewmueller** [comment]
Hey @joshhopkins! I agree that it can be a useful feature. Since Prisma 2 is not really tied to GraphQL anymore, the API doesn't make as much sense for us.

That being said, we may end up exposing the internal query protocol sometime in the future. 

How do you currently use `$graphql`?

**Comment by joshhopkins** [comment]
For more complex cases where bindings aren't needed, I often create my own interface using GraphQL. It works well and is consistent with how we think on the frontend.

**Comment by schickling** [comment]
@joshhopkins have you seen the new `select` API? This should be a better replacement. Can you confirm whether this solves your question?

**Comment by janpio** [comment]
Remind @joshhopkins 🐰
