### ISSUE TITLE
Cannot find module '@generated/photon'

### ISSUE THREAD

**Issue by anddizu** [prisma/photonjs#56]
when i use prisma2 init to generate a new project and run:

```
yarn run v1.17.0
$ ts-node prisma/seed.ts

/Users/a/Downloads/prisma2/node_modules/ts-node/src/index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
prisma/seed.ts:1:20 - error TS2307: Cannot find module '@generated/photon'.

1 import Photon from '@generated/photon'
```

**Comment by Cerberus** [comment]
Have you tried `prisma2 generate` ?

1). Create a new migration
```
prisma2 lift save --name 'init'
```
2). Migrate your database up
```
prisma2 up
```
3). Generate Photon
```
prisma2 generate
```

**Comment by rwoody** [comment]
Same issue for me but when running the graphql-auth example and `npm start`

**Comment by divyenduz** [comment]
This issue has been resolved in the latest CLI version `0.0.95`, please install it using `npm install -g prisma2` and try again.

**Comment by matthewmueller** [comment]
Closing. We can reopen if it's still an issue :-)

**Comment by lednhatkhanh** [comment]
Still happening for me with `prisma2@0.0.114`

**Comment by divyenduz** [comment]
@lednhatkhanh : Can you please share your Prisms schema file? (`project.prisma`)

**Comment by lednhatkhanh** [comment]
@divyenduz I have a simple model file just like this:

```
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}

generator photon {
  provider = "photonjs"
}

generator nexus_prisma {
  provider = "nexus-prisma"
  output   = "node_modules/@generated/nexus-prisma"
}

model User {
  id          String       @default(cuid()) @id @unique
  email       String       @unique
  name        String
  coffeeShops CoffeeShop[]
  password    String
}

model CoffeeShop {
  id        String   @default(cuid()) @id @unique
  name      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  wifi      Boolean
  maxPrice  Float
  minPrice  Float
  openAt    DateTime
  closeAt   DateTime
  address   String
  mapsUrl   String
  createdBy User
  mainImage String
}
```

`typescript: 3.5.2`, `@prisma/nexus: 0.0.1`, `prisma2: 0.0.114`

**Comment by z2x** [comment]
prisma2@0.0.114 is same error

**Comment by EdoardoVarani** [comment]
prisma2@0.0.114 same error on Linux Mint

**Comment by divyenduz** [comment]
After each `yarn`/`npm` install operation, the `node_modules` are made pristine by the respective package managers, this removes all generated code such as Photon. The solution is to use "prisma2 generate" as a `postinstall` hook. 

This document talks more about this design decision: https://github.com/prisma/prisma2/blob/537234fc6795321141af00f2c19d82ec437c698f/docs/photon/codegen-and-node-setup.md#photon-js-should-be-viewed-as-an-npm-package

Please let me know if this issue is fixed for you after adding the `postinstall` hook.

**Comment by ManAnRuck** [comment]
@divyenduz for me it doesn't resolve the issue :/

`prisma2@2.0.0-preview-2, binary version: 4f33077038a490e4b2c1c260f109309e4a447181`

<img width="1661" alt="Bildschirmfoto 2019-07-23 um 09 10 33" src="https://user-images.githubusercontent.com/2183135/61690626-112e7600-ad2a-11e9-8a32-5f862fb37e28.png">

**Comment by gihrig** [comment]
@divyenduz A change in preview-2 requires that you remove the `output` property from

```
generator nexus_prisma {
  provider = "nexus-prisma"
  output   = "node_modules/@generated/nexus-prisma"
}
```
See #143 for details.

**Comment by ManAnRuck** [comment]
@gihrig after removing output it was working (and remove and reinstall node_modules folders)

**Comment by timsuchanek** [comment]
It sounds like this can be closed, as removing a hardcoded `output` fixes it.

**Comment by dojsys** [comment]
Can we use photon in client side app like Angular or React?

**Comment by janpio** [comment]
Good question @dojsys, you should create a new issue for this question though. Thanks.
