### ISSUE TITLE
Support for selecting relations of relations (and more sophisticated queries in general)

### ISSUE THREAD

**Issue by artemzakharov** [prisma/photonjs#70]
Perhaps I'm missing something in the documentation, but I can't find anything that describes how to select relations that are more than one layer deep. The example I found is this:

```
// The returned posts objects will have all scalar fields of the `Post` model and additionally all the categories for each post
const allPosts: Post[] = await photon.posts.findMany({
  include: ["categories"]
})
```

Okay, this gets me the `categories` on each returned `post`, but what if I want to also grab one or more relations of each returned `category`? I can't see any way to do that right now since `include` just takes a string array, not any kind of JSON object where i could specify what fields on each `category` I'd want returned (and iteratively go deeper if needed)

The GraphQL equivalent of what I'd like to be able to do is something like this:

```
{
 posts {
   id
   categories {
      id
      x {
        id
      } 
      y {
        id
      }
    }
 }
}
```

I stayed away from Prisma Client (and stuck with Bindings) precisely because it seemed to offer no support for these kinds of sophisticated queries; the fluid API was kind of neat for extremely simple use cases, but hopeless for anything beyond that. Is Photon limited in the same fashion? 

I'd really like it if I could select data with Photon in a way similar to this:

```
// The returned posts objects will have all scalar fields of the `Post` model and additionally all the categories for each post
const allPosts: Post[] = await photon.posts.findMany({
  include: {
    id: true,
    categories: {
      id: true,
      x: {
        id: true
      },
      y: {
        id: true
      }
    }
  }
})
```

**Comment by matthewmueller** [comment]
Hi @artemzakharov! Thanks for bringing this up. We're still working on our documentation, but you should be able to use the select API to get nested data:

**project.prisma**

```groovy
datasource pg {
  provider = "sqlite"
  url      = "file:demo.db"
}

generator photon {
  provider = "photonjs"
  output   = "node_modules/@generated/photon"
}

model User {
  id    Int    @id
  email String @unique
  name  String
  posts Post[]
}

model Post {
  id    Int    @id
  user  User
  title String
}
```

**main.ts**

```js
import Photon from '@generated/photon'

async function main() {
  const photon = new Photon()
  await photon.connect()

  // await photon.users.create({
  //   data: {
  //     email: 'mueller@prisma.io',
  //     name: 'Matt',
  //     posts: {
  //       create: [{ title: 'First Post' }, { title: 'Second post' }],
  //     },
  //   },
  // })

  const users = await photon.users.findMany({
    where: {
      email: 'mueller@prisma.io',
    },
    select: {
      name: true,
      email: true,
      posts: {
        last: 1,
        select: {
          title: true,
        },
      },
    },
  })

  console.dir(users, { depth: Infinity })

  await photon.disconnect()
}

main().catch(console.error)
```

**Result**

```
[
  {
    name: 'Matt',
    email: 'mueller@prisma.io',
    posts: [ { title: 'Second post' } ]
  }
]
```

**Comment by iherger** [comment]
I just discovered this.

From my point of view, nested reads (using `select` and/or `include`) is actually really nice and very powerful. 

Unfortunately, I don't think this sufficiently described in the documentation, so I would suggest to  add a paragraph about nested reads.
