### ISSUE TITLE
Inconsistent type generation

### ISSUE THREAD

**Issue by schickling** [prisma/photonjs#78]
Are we treating the field name `id` somehow special? For `model Blog { id Int @id }` I don’t have the provide `id` in Photon but for `model PostNews { new Int @id }` I *do* have to provide the `new` field.

![image](https://user-images.githubusercontent.com/1567498/59362395-a99d0800-8d33-11e9-8a78-01097b6922a0.png)
![image](https://user-images.githubusercontent.com/1567498/59362408-b02b7f80-8d33-11e9-9fc8-22f5c0166b7b.png)

**Comment by dpetrick** [comment]
The query engine doesn't treat fields differently as far as I know. This is either an error in photon (likely) or the migration engine / datamodel converter (unlikely).

**Comment by pantharshit00** [comment]
I can still reproduce this

**Comment by mavilein** [comment]
A fix is available in `alpha`.
