### ISSUE TITLE
Update model args are always required for required fields

### ISSUE THREAD

**Issue by divyenduz** [prisma/photonjs#80]
![image](https://user-images.githubusercontent.com/746482/59343072-557e2d80-8d0b-11e9-8dc5-f7ac397c7a62.png)

**Comment by pantharshit00** [comment]
This is fixed now.

![image](https://user-images.githubusercontent.com/22195362/60340956-af008080-99ca-11e9-9cfa-2261f73c3ac2.png)

Required properties are optional in the update input as the intended design.
